export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as HowItWorks } from './HowItWorks';
export { default as Gallery } from './Gallery';
export { default as Features } from './Features';
export { default as FAQ } from './FAQ';
export { default as Pricing } from './Pricing';
export { default as Footer } from './Footer';
export { default as FloatingWhatsApp } from './FloatingWhatsApp';
